# Generated by Django 4.1.2 on 2022-10-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=200),
            preserve_default=False,
        ),
    ]
