# Generated by Django 4.1.2 on 2022-11-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0013_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
